### ISSUE TITLE
hello paper link not work

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/omni3d#1]
any paper link?

**Comment by gkioxari** [comment]
Soon.....

**Comment by jinfagang** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/21303438/179735314-1fc84caa-ac77-4416-b4b3-8aaafc63804c.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/21303438/179735336-950be3cf-04d2-4876-86a1-8b3feab42cd5.png">

**Comment by gkioxari** [comment]
lolz!! I will personally deliver the arxiv link to you when the paper is out.
