### ISSUE TITLE
ReNet34 yaml not working

### ISSUE THREAD

**Issue by ocissor** [facebookresearch/omni3d#15]
Hi, I was trying to run the demo by passing the ResNet34 yaml file and the Res34 pth file for model weights as the argument but I was prompted with an error _**urllib.error.HTTPError: HTTP Error 403: Forbidden**_. Can you please help me resolve this issue?
Thank you.

**Comment by ocissor** [comment]
> You were probably not able to download the model I suspect. This has nothing to do with the yaml

yes I am not able to download the model any solution for it?

**Comment by gkioxari** [comment]
The models are here: https://github.com/facebookresearch/omni3d/blob/main/MODEL_ZOO.md

If you can't download them using our code (perhaps you have a wall?) then just download them manually and place them in the right location.
