### ISSUE TITLE
where is the file named category_meta.json

### ISSUE THREAD

**Issue by yexiguafuqihao** [facebookresearch/omni3d#18]
HI, thanks for your great work. I'm going to run the demo script demo.py. When everything was prepared, there is an error occurred, implying the file of  category_meta.json missed. Thus, I'm curious about where can I get the file.

**Comment by gkioxari** [comment]
When you run the demo, the path handler should download the category_meta.json. The path handler tries to fetch it from S3: [here](https://github.com/facebookresearch/omni3d/blob/main/cubercnn/util/model_zoo.py#L12). 

This likely is not happening in your case. This commend might help you: https://github.com/facebookresearch/omni3d/issues/3#issuecomment-1201320606

**Comment by yexiguafuqihao** [comment]
Thank you.
