### ISSUE TITLE
Script for converting objectron to omni3d format

### ISSUE THREAD

**Issue by YangHai-1218** [facebookresearch/omni3d#39]
Hey, I noticed that omni3d only uses a small fraction of the original objectron dataset. And I am trying to cover more data in objectron. Can you provide the script for converting the objectron data format to omni3d format? Just convert the objectron coordinate to omni3d coordinate is enough.

**Comment by Lizhuoling** [comment]
Hi, I have a similar concern as you. Could you share with me how you tackle the above problem? I want to obtain the depth point of objection images in Omni3D.
