### ISSUE TITLE
training kitti only

### ISSUE THREAD

**Issue by Sondosmohamed1** [facebookresearch/omni3d#43]
Hello and thank you very much for this Great work , i am trying to train only kitti because i want to replace it with my custom dataset in kitti format 
  i changed  he confi _out
  _BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  #TRAIN: ('nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val')
  #TRAIN: ('KITTI_train')
  #TEST: ('nuScenes_test', 'KITTI_test') 
  TRAIN: ('KITTI_train', 'KITTI_val',)
  TEST: ('KITTI_val',)
  CATEGORY_NAMES: ('cyclist', 'pedestrian', 'trailer', 'bus', 'motorcycle', 'car', 'barrier', 'truck', 'van', 'traffic cone', 'bicycle')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 11
  
  but  when i run the training command (python tools/train_net.py   --config-file configs/Base_Omni3D_out.yaml --num-gpus 1   SOLVER.IMS_PER_BATCH 1 SOLVER.BASE_LR 0.0025   SOLVER.MAX_ITER 5568000 SOLVER.STEPS "(3340800, 4454400)" ) i got this problem 
  
  File "tools/train_net.py", line 508, in <module>
    launch(
  File "/home/sun/anaconda3/envs/cubercnn/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "tools/train_net.py", line 462, in main
    if do_train(cfg, model, dataset_id_to_unknown_cats, dataset_id_to_src, resume=args.resume):
  File "tools/train_net.py", line 137, in do_train
    data_loader = build_detection_train_loader(cfg, mapper=data_mapper, dataset_id_to_src=dataset_id_to_src)
  File "/home/sun/anaconda3/envs/cubercnn/lib/python3.8/site-packages/detectron2/config/config.py", line 208, in wrapped
    return orig_func(**explicit_args)
  File "/home/sun/Downloads/omni3d-main/cubercnn/data/build.py", line 189, in build_detection_train_loader
    return build_batch_data_loader(
  File "/home/sun/anaconda3/envs/cubercnn/lib/python3.8/site-packages/detectron2/data/build.py", line 339, in build_batch_data_loader
    data_loader = torchdata.DataLoader(
  File "/home/sun/anaconda3/envs/cubercnn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 243, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

 could you help , thank you very much

**Comment by Sondosmohamed1** [comment]
i found the solution the problem from detectron2 i used different version ,therefore i overwrite the function to not accept prefetch_factor ant it worked

**Comment by Sondosmohamed1** [comment]
i found the solution the problem from detectron2 i used different version ,therefore i overwrite the function to not accept prefetch_factor ant it worked

**Comment by star9988rr** [comment]
Hi, @Sondosmohamed1, have you reproduced the results of KITTI? What hyper-parameters did you use?

**Comment by Sondosmohamed1** [comment]
Hi, I did not reproduce KITT, but I worked with a custom dataset having the same KITTI format, and it works. You could start with the same hyperparameters provided by the GitHub repository, then try to readjust the learning rate (try increasing it), batch size (try increasing it), etc., if the first option does not work.

**Comment by star9988rr** [comment]
Thanks a lot! When I increase the batch size, should the number of steps decrease accordingly? Have you encountered issues with unstable convergence? For example, "WARNING: Skipping gradient update due to inf/nan detection." Will this affect the final results?

**Comment by Sondosmohamed1** [comment]
Yes, I decreased the number of steps. Yes, I encountered unstable convergence and encountered skipping gradients, but because after skipping, the training starts from the beginning, I used the checkpoints to avoid that and it works . Frankly, I still have some NaN results in some AP values during validation . I am still working on training , but the AP by category works. Also, the visualization indicates convergence

**Comment by star9988rr** [comment]
Thanks you very much!

**Comment by mason1008** [comment]
Hi, @Sondosmohamed1, Is there a relationship between the number of images in the training dataset and MAX_ITER? Could you please provide the number of images in your custom dataset along with the hyperparameters that correspond to the best results?

**Comment by Sondosmohamed1** [comment]
Hi, according to the tips, there is a relationship between batch size and the maximum number of iterations. In my case, I used the same configuration as when training on a single GPU. However, I didn’t reach the maximum number of iterations because I encountered sudden divergence and instability during training. I then reduced the maximum iterations to 250k, which led to better results. However , my advice is to start with their recommended configuration and monitor training stability then change .

**Comment by mason1008** [comment]
Thank you very much. However, I wasn't referring to the relationship between batch size and MAX_ITER. Omni3D has 194,700 training images, while KITTI only has 3,712 training images. Does the MAX_ITER for a single GPU remain at 5,568,000 in both cases? Is there a relationship between MAX_ITER and the number of training images? How many training images are in your dataset?

**Comment by Sondosmohamed1** [comment]
I used around 75k images during this experiment. Also, you could try splitting the Omni3D dataset into KITTI, nuScenes, etc., and observe the effect of the number of images on max iterations. You could test different max iterations.
