### ISSUE TITLE
Any plan to release the dataset

### ISSUE THREAD

**Issue by longbowzhang** [facebookresearch/omni3d#7]
Hi authors of omni3d,

Thanks for your superb work. I am just wondering do you have any plan to release the dataset?

**Comment by gkioxari** [comment]
Very very soon! Stay tuned!

**Comment by gkioxari** [comment]
Coming very soon I promise. We are in the final stages of internal legal review

**Comment by gkioxari** [comment]
Data, training code, inference and instructions now released: https://github.com/facebookresearch/omni3d
