### ISSUE TITLE
Question about Tracking in readme

### ISSUE THREAD

**Issue by ChiyuanFeng** [facebookresearch/omni3d#9]
Hello, 
May I get more info about the tracking algorithm showed in readme page?

Thanks

**Comment by gkioxari** [comment]
In the readme we provide the association losses we use for tracking. Do you have concrete questions for us?

**Comment by rpartsey** [comment]
Hi @gkioxari,
Are you going to release the tracking algorithm code in the future?
Thanks in advance for your answer.
